#pragma config(Sensor, port2,  leftLED,        sensorVexIQ_LED)
#pragma config(Sensor, port3,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  bumpSensor,     sensorVexIQ_Touch)
#pragma config(Sensor, port9,  colorSensor,    sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, rightLED,       sensorVexIQ_LED)
#pragma config(Sensor, port8,  thirdLED,       sensorVexIQ_LED)
#pragma config(Motor,  motor1,          Right,         tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor4,          CubeCatcher,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          BallCatcher,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          Left,          tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor10,         Shift,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         Arm,           tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//define global variable
int turning;
int threshold = 200; //white ~ 500; black ~ 50 (gray scale)

//============================================| TASK LowGreenCube |============================================
task LowGreenCube()
{
	while(true)
	{
		/*Touch LED sensor to start the autonuous program*/
		waitUntil(getTouchLEDValue(rightLED) == 1);

		resetGyro(gyroSensor);

		setMotorTarget(Arm, -400, 80); //lower the arm
		wait1Msec(500);

		//slow start to avoid wheel slippery
		resetMotorEncoder(Left);
		resetMotorEncoder(Right);
		setMotorTarget(Left, 155, 10);
		setMotorTarget(Right, 155, 10);
		wait1Msec(50);
		setMotorTarget(Left, 155, 20);
		setMotorTarget(Right, 155, 20);
		wait1Msec(50);
		setMotorTarget(Left, 155, 30);
		setMotorTarget(Right, 155, 30);
		waitUntilMotorStop(Left);
		waitUntilMotorStop(Right);
		wait1Msec(500);

		resetMotorEncoder(Left);
		resetMotorEncoder(Right);
		resetMotorEncoder(Arm);
		setMotorTarget(Left, 40, 15);
		setMotorTarget(Right, 40, 15);
		wait1Msec(50);
		setMotorTarget(Arm, 260, 60);
		waitUntilMotorStop(Left);
		waitUntilMotorStop(Right);
		waitUntilMotorStop(Arm);
		wait1Msec(500);

		//drive forward to low platform
		clearTimer(T1);
		while(time1[T1] < 2000) //1200
		{
			setMotorSpeed(Left, 40);
			setMotorSpeed(Right, 40);
			//if(getColorValue(colorSensor) < threshold) //detect black
			//{
			//	// counter-steer left:
			//	setMotorSpeed(Left, 70);
			//	setMotorSpeed(Right, 85);
			//}
			//else
			//{
			//	// counter-steer right:
			//	setMotorSpeed(Left, 85);
			//	setMotorSpeed(Right, 70);
			//}
		}
		setMotorSpeed(Left, 0);
		setMotorSpeed(Right, 0);
		wait1Msec(100);

		//lower arm to deposite 1st green cube
		resetMotorEncoder(Arm);
		setMotorTarget(Arm, -100, 30);
		waitUntilMotorStop(Arm);
		wait1Msec(500);

		//back up
		resetMotorEncoder(Left);
		resetMotorEncoder(Right);
		setMotorTarget(Left, -200, 80);
		setMotorTarget(Right, -200, 80);
		waitUntilMotorStop(Left);
		waitUntilMotorStop(Right);
		wait1Msec(100);
	}
}
//============================================| TASK LowGreenCube |============================================

//============================================| TASK HighGreenCube |============================================
task HighGreenCube()
{
	while(true)
	{
		/*Touch LED sensor to start the autonuous program*/
		waitUntil(getTouchLEDValue(leftLED) == 1);

		setMotorTarget(Arm, -400, 80); //lower the arm

		//raise ballcatcher
		resetMotorEncoder(BallCatcher);
		setMotorTarget(BallCatcher, 50, 80);
		waitUntilMotorStop(BallCatcher);
		wait1Msec(500);

		//turn left
		resetGyro(gyroSensor);
		while(getGyroDegrees(gyroSensor) < 75)
		{
			turning = getGyroDegrees(gyroSensor);
			setMotorSpeed(Left, -50+turning/2);
			setMotorSpeed(Right, +50-turning/2);
		}
		setMotorSpeed(Left, 0);
		setMotorSpeed(Right, 0);
		wait1Msec(500);


		//forward
		resetMotorEncoder(Left);
		resetMotorEncoder(Right);
		setMotorTarget(Left, 420, 30);
		setMotorTarget(Right, 420, 30);
		waitUntilMotorStop(Left);
		waitUntilMotorStop(Right);
		wait1Msec(500);

		//turn right towards green cube
		resetGyro(gyroSensor);
		while(getGyroDegrees(gyroSensor) > -23)
		{
			turning = getGyroDegrees(gyroSensor);
			setMotorSpeed(Left, 50+turning/2);
			setMotorSpeed(Right, -50-turning/2);
		}
		setMotorSpeed(Left, 0);
		setMotorSpeed(Right, 0);
		wait1Msec(500);

		//forward to pick up green cube
		resetMotorEncoder(Left);
		resetMotorEncoder(Right);
		setMotorTarget(Left,200, 30);
		setMotorTarget(Right, 200, 30);
		waitUntilMotorStop(Left);
		waitUntilMotorStop(Right);
		wait1Msec(500);

		//pick up green cube
		resetMotorEncoder(Arm);
		while(getBumperValue(bumpSensor) == 0)
		{
			setMotorSpeed(Arm, 100);
		}
		setMotorSpeed(Arm, 0);
		wait1Msec(500);

		//back up
		resetMotorEncoder(Left);
		resetMotorEncoder(Right);
		setMotorTarget(Left, -310, 50);
		setMotorTarget(Right, -310, 50);
		waitUntilMotorStop(Left);
		waitUntilMotorStop(Right);
		wait1Msec(500);

		//turn left again
		resetGyro(gyroSensor);
		turning = getGyroDegrees(gyroSensor);
		while(getGyroDegrees(gyroSensor) < 60)
		{
			setMotorSpeed(Left, -50+turning/2);
			setMotorSpeed(Right, +50-turning/2);
		}
		setMotorSpeed(Left, 0);
		setMotorSpeed(Right, 0);
		wait1Msec(500);

		//forward
		resetMotorEncoder(Left);
		resetMotorEncoder(Right);
		setMotorTarget(Left, 160, 30);
		setMotorTarget(Right, 160, 30);
		waitUntilMotorStop(Left);
		waitUntilMotorStop(Right);
		wait1Msec(500);

		//shift into position
		resetMotorEncoder(Shift);
		setMotorTarget(Shift, -330, 50);
		waitUntilMotorStop(Shift);
		wait1Msec(500);

		//deposite green cube on high platform
		resetMotorEncoder(Arm);
		setMotorTarget(Arm, -100, 30);
		waitUntilMotorStop(Arm);
		wait1Msec(500);

		//back up
		resetMotorEncoder(Left);
		resetMotorEncoder(Right);
		setMotorTarget(Left, -160, 50);
		setMotorTarget(Right, -160, 50);
		waitUntilMotorStop(Left);
		waitUntilMotorStop(Right);
		wait1Msec(500);

		//lower ballcatcher
		resetMotorEncoder(BallCatcher);
		setMotorTarget(BallCatcher, -50, 80);
		waitUntilMotorStop(BallCatcher);
		wait1Msec(500);
	}
}
//============================================| TASK HighGreenCube |=============================================




task main()
{
	/*initialization steps start*/
	setTouchLEDColor(rightLED, colorRed); //start initialization steps

	//reset sensors/encoders
	resetGyro(gyroSensor); //Reset gyro sensor to 0 reading
	resetMotorEncoder(BallCatcher); //Reset BsllCatcher motor encoder to 0 position
	resetMotorEncoder(Arm); //Reset Arm motor encoder to 0 position

	//Calibrate gyro sensor
	startGyroCalibration(gyroSensor, gyroCalibrateSamples1024); // longer cal, works better
	wait1Msec(100);
	// wait for calibration to finish
	while(getGyroCalibrationFlag(gyroSensor))
	{
		displayTextLine(1, "Calibrating... %02d");
		wait1Msec(100);
	}

	//Gyro sensor calibration completed
	setTouchLEDColor(rightLED, colorGreen);
	setTouchLEDColor(leftLED, colorBlue);
	playSound(soundTada);
	eraseDisplay();
	resetGyro(gyroSensor);
	/*initialization steps complete*/


	/*autonomous program starts here*/
	startTask(LowGreenCube);   // start task LowGreenCube
	startTask(HighGreenCube);  // start task HighGreenCube

	while(true)
	{
		sleep(25); // Keep the program alive, but let the other tasks have the processor by "sleeping"
	}
	/*autonomous program ends here*/

}
